### ISSUE TITLE
Train a model on new 10x larger ensemble dataset

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#138]
@spencerkclark is generating a new dataset with 10x as much data. There are some steps we need to do before we'll be able to train on this dataset. This is a meta-issue to track those steps.

New features required:
- [x] ai2cm/ace#123
- [x] ai2cm/ace#134 
- [x] ai2cm/ace#139 
- [x] ai2cm/ace#144 

Data generation/processing tasks:
- [x] ai2cm/ace#132 
- [x] ai2cm/ace#133 
- [x] ai2cm/ace#135 
- [x] ai2cm/ace-internal-test#81 
- [x] ai2cm/full-model#165

**Comment by oliverwm1** [comment]
This is happening!
