### ISSUE TITLE
TODO for nice figures

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/ace#205]
Some items that need to happen to get the figures needed for a paper:

- [x] compute TWP derived variable (#322)
- [x] enable saving only some output variables to netCDF from inference (#294)
- [ ] enable saving derived diagnostics (like time-mean maps) to a netCDF to allow custom plots (#298)
- [ ] do 100-year simulation (need to deal with ai2cm/ace#207 first)

**Comment by oliverwm1** [comment]
Resolving this meta-issue. Can track individual items through their respective issues.
