### ISSUE TITLE
Enable inference rollouts that only require initial condition and forcing data

### ISSUE THREAD

**Issue by gideonite** [ai2cm/ace#258]
It is a common atmospheric modeling use case to do simulations where only have the initial condition and forcing data are available, but the reference target data (which is currently used for computing error metrics online) is not available. It would be useful to generalize the inference code so that it could run only using the initial condition and forcing data. We have previously worked around this by repeating the entire dataset (#397) but this works only for certain edge cases, e.g. with repeating forcing.

These are some implementation ideas:

1. Repeat the initial condition variables to fill the missing "target" variables.
1. Fill target data with NaNs → it seems like this is no better than repeating the data, and likely much more complex
1. Handle these type of inference runs as an edge case, while keeping the existing inference code in place → this seems quite complex. It would be helpful to know what the downstream use cases are so that we can evaluate the importance of implementing these edge cases.
1. Write a new inference class whose members do not require `target` → Perhaps the cleanest but would likely result in duplicated code.

Using this as a meta issue. Here are related issues which need to be resolved before this issue can be directly tackled:
- [x] ai2cm/full-model#663 
- [x] ai2cm/full-model#756 
- [x] ai2cm/full-model#758
